# Generated by Django 5.0.2 on 2024-02-20 22:48

import backend.utils.date_time
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10)),
                ('course_description', models.TextField()),
                ('course_credit', models.IntegerField()),
                ('course_status', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True)),
                ('course_application_link', models.URLField(blank=True)),
                ('course_image', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='MNFAPAC_PROJECT/courses/')),
                ('created_at', models.DateTimeField(default=backend.utils.date_time.get_current_datetime)),
                ('updated_at', models.DateTimeField(default=backend.utils.date_time.get_current_datetime)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('created_at',),
            },
        ),
    ]
